import { AMENITY_FILTER_I18N, DESTINATIONS_I18N, PRICE_RANGE, STAR_RATINGS } from '@/pages/Destinations/const'

export const FILTER_I18N = DESTINATIONS_I18N.filters
export const FILTER_PRICE_RANGE = PRICE_RANGE
export const FILTER_STAR_RATINGS = STAR_RATINGS
export const FILTER_AMENITY_I18N = AMENITY_FILTER_I18N
